name: Sync Fork

on:
  schedule:
    - cron: '0 5 * * *' # Run every morning at 5
  workflow_dispatch: # Run on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: mani-sh-reddy
          base: master
          head: master
          ignore_fail: true
